### ISSUE TITLE
在小程序中使用图标字体

### ISSUE THREAD

**Issue by huangzilong** [huangzilong/Notes#28]
## 在小程序中使用图标字体

在小程序中使用`.ttf`形式的图标字体，会有一些问题，例如在ios下，图标不能正常显示。

```css
@font-face {
    font-family: 'icon';
    src: url('~@/assets/symbols.ttf') format('truetype');
}
```

这个使用可以使用[https://transfonter.org/](https://transfonter.org/)将图标字体转换成base64形式的css使用。

![screen shot 2017-10-11 at 19 45 15](https://user-images.githubusercontent.com/5485065/31439105-8ae345d2-ae50-11e7-8e8d-5a1b4e788ea8.png)

```css
@font-face {
	font-family: 'icon';
    src: 'base 64';
    font-weight: normal;
	font-style: normal;
}
```
